name: Docker Build & Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker Image
        run: docker build -t fersanbar/mono-api:${{ github.sha }} .

      - name: Tag Latest
        run: docker tag fersanbar/mono-api:${{ github.sha }} fersanbar/mono-api:latest

      - name: Push Docker Image
        run: | 
          docker push fersanbar/fersanbar/mono-api:${{ github.sha }}
          docker push fersanbar/fersanbar/mono-api:latest
